CREATE TABLE policy_sets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code     VARCHAR(64)  NOT NULL,
    name            VARCHAR(256) NOT NULL,
    version         INT          NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    effective_from  TIMESTAMP WITH TIME ZONE,
    effective_to    TIMESTAMP WITH TIME ZONE,
    priority        INT          NOT NULL DEFAULT 100,
    created_by      VARCHAR(128),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_policy_code_version UNIQUE (policy_code, version),
    CONSTRAINT chk_policy_status CHECK (status IN ('DRAFT', 'ACTIVE', 'DEPRECATED'))
);

CREATE TABLE policy_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_set_id    BIGINT       NOT NULL,
    rule_code        VARCHAR(64)  NOT NULL,
    rule_type        VARCHAR(32)  NOT NULL,
    conditions_json  JSON         NOT NULL DEFAULT '{}',
    action           VARCHAR(16)  NOT NULL,
    reason_template  VARCHAR(512),
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_policy_rule_code UNIQUE (policy_set_id, rule_code),
    CONSTRAINT fk_policy_rules_set FOREIGN KEY (policy_set_id) REFERENCES policy_sets(id) ON DELETE CASCADE
);

CREATE TABLE country_profiles (
    country_code    VARCHAR(8)   PRIMARY KEY,
    tier            VARCHAR(8)   NOT NULL,
    is_allowed      BOOLEAN      NOT NULL DEFAULT TRUE,
    trade_allowed   BOOLEAN      NOT NULL DEFAULT TRUE,
    custody_allowed BOOLEAN      NOT NULL DEFAULT TRUE,
    notes           CLOB,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE compliance_decisions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          VARCHAR(64)  NOT NULL,
    subject_id          VARCHAR(256),
    ip_hash             VARCHAR(128),
    ip_masked           VARCHAR(64),
    country_code        VARCHAR(8),
    region              VARCHAR(64),
    action_type         VARCHAR(32)  NOT NULL,
    decision            VARCHAR(16)  NOT NULL,
    matched_policy_code VARCHAR(64),
    matched_rule_code   VARCHAR(64),
    reason              VARCHAR(512),
    policy_version      INT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE policy_audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor        VARCHAR(128) NOT NULL,
    action       VARCHAR(64)  NOT NULL,
    entity_type  VARCHAR(64)  NOT NULL,
    entity_id    VARCHAR(128) NOT NULL,
    before_json  JSON,
    after_json   JSON,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
